server {
    listen 80;
    server_name localhost;

    # Основной блок для путей, начинающихся с /erp_docs/
    location /erp_docs/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /erp_docs/index.html;

        # Вложенный блок для ассетов внутри erp_docs
        location /erp_docs/assets/ {
            alias /usr/share/nginx/html/assets/;
            access_log off;
            expires 1y;
            add_header Cache-Control "public, no-transform";
        }
    }

    # Редирект с корня на /erp_docs/, если нужно
    location = / {
        return 301 /erp_docs/;
    }
}